name: tissue_forge_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

variables:
  tf_version: '0.2.1'
  tf_buildnum: 0
  tf_buildqual: 'release'

parameters:
- name: py_minor_versions_win
  type: object
  default: [8, 9, 10, 11]
- name: py_minor_versions_linux
  type: object
  default: [8, 9, 10, 11]
- name: py_minor_versions_osx
  type: object
  default: [8, 9, 10]
- name: py_minor_versions_conda
  type: object
  default: [8, 9, 10, 11]

stages:

  # Windows build: local

  - stage: TissueForgeBuildWindowsLocal
    displayName: Local build for Windows
    pool:
      vmImage: 'windows-2019'
    dependsOn: []
    jobs:
      - ${{ each py_minor_version in parameters.py_minor_versions_win }}:
        - template: job-templates/job-build-test-package-win-local.yml
          parameters:
            name: ${{ format('TissueForgeBuildWindowsLocal_Python_3_{0}', py_minor_version) }}
            platform_name: 'win64'
            tf_buildqual: $(tf_buildqual)
            py_minor_version: ${{ py_minor_version }}
            working_dir: $(Agent.BuildDirectory)
            staging_dir: $(Build.ArtifactStagingDirectory)

  # Linux build: local

  - stage: TissueForgeBuildLinuxLocal
    displayName: Local build for Linux
    pool: 
      vmImage: 'ubuntu-20.04'
    dependsOn: []
    jobs:
      - ${{ each py_minor_version in parameters.py_minor_versions_linux }}:
        - template: job-templates/job-build-test-package-linux-local.yml
          parameters:
            name: ${{ format('TissueForgeBuildLinuxLocal_Python_3_{0}', py_minor_version) }}
            platform_name: 'linux64'
            tf_buildqual: $(tf_buildqual)
            py_minor_version: ${{ py_minor_version }}
            working_dir: $(Agent.BuildDirectory)
            staging_dir: $(Build.ArtifactStagingDirectory)

  # MacOS build: local

  - stage: TissueForgeBuildMacLocal
    displayName: Local build for Mac
    pool: 
      vmImage: 'macOS-11'
    dependsOn: []
    jobs:
      - ${{ each py_minor_version in parameters.py_minor_versions_osx }}:
        - template: job-templates/job-build-test-package-osx-local.yml
          parameters:
            name: ${{ format('TissueForgeBuildMacLocal_Python_3_{0}', py_minor_version) }}
            platform_name: 'osx64'
            tf_buildqual: $(tf_buildqual)
            py_minor_version: ${{ py_minor_version }}
            working_dir: $(Agent.BuildDirectory)
            staging_dir: $(Build.ArtifactStagingDirectory)

  # Windows build: conda

  - stage: TissueForgeBuildWindowsConda
    displayName: Conda build for Windows
    pool:
      vmImage: 'windows-2019'
    dependsOn: []
    jobs:
      - ${{ each py_minor_version in parameters.py_minor_versions_conda }}:
        - template: job-templates/job-build-test-package-win-conda.yml
          parameters:
            name: ${{ format('TissueForgeBuildWindowsConda_Python_3_{0}', py_minor_version) }}
            platform_name: 'win64'
            tf_buildqual: $(tf_buildqual)
            py_minor_version: ${{ py_minor_version }}
            working_dir: $(Agent.BuildDirectory)
            staging_dir: $(Build.ArtifactStagingDirectory)
            tf_version: $(tf_version)
            tf_buildnum: $(tf_buildnum)

  # Linux build: conda

  - stage: TissueForgeBuildLinuxConda
    displayName: Conda build for Linux
    pool:
      vmImage: 'ubuntu-20.04'
    dependsOn: []
    jobs:
      - ${{ each py_minor_version in parameters.py_minor_versions_conda }}:
        - template: job-templates/job-build-test-package-linux-conda.yml
          parameters:
            name: ${{ format('TissueForgeBuildLinuxConda_Python_3_{0}', py_minor_version) }}
            platform_name: 'linux64'
            tf_buildqual: $(tf_buildqual)
            py_minor_version: ${{ py_minor_version }}
            working_dir: $(Agent.BuildDirectory)
            staging_dir: $(Build.ArtifactStagingDirectory)
            tf_version: $(tf_version)
            tf_buildnum: $(tf_buildnum)

  # MacOS build: conda

  - stage: TissueForgeBuildMacConda
    displayName: Conda build for Mac
    pool:
      vmImage: 'macOS-11'
    dependsOn: []
    jobs:
      - ${{ each py_minor_version in parameters.py_minor_versions_conda }}:
        - template: job-templates/job-build-test-package-osx-conda.yml
          parameters:
            name: ${{ format('TissueForgeBuildMacConda_Python_3_{0}', py_minor_version) }}
            platform_name: 'osx64'
            tf_buildqual: $(tf_buildqual)
            py_minor_version: ${{ py_minor_version }}
            working_dir: $(Agent.BuildDirectory)
            staging_dir: $(Build.ArtifactStagingDirectory)
            tf_version: $(tf_version)
            tf_buildnum: $(tf_buildnum)
